name: Build PPA

on:
  workflow_dispatch:

env:
  base-dir: 'ppa'
  list-name: 'csutorasa'

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GNUPG
        shell: bash
        run: "sudo apt-get install -y gnupg"
      
      - name: Import gpg key
        shell: bash
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" | gpg --import
      
      - name: Create KEY.gpg
        shell: bash
        working-directory: ${{ env.base-dir }}
        run: gpg --armor --export > KEY.gpg
      
      - name: Create Pagackes
        shell: bash
        working-directory: ${{ env.base-dir }}
        run: |
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
      
      - name: Create Release
        shell: bash
        working-directory: ${{ env.base-dir }}
        run: |
          apt-ftparchive release . > Release
          gpg -abs -o - Release > Release.gpg
          gpg --clearsign -o - Release > InRelease

      - name: Create .list
        shell: bash
        working-directory: ${{ env.base-dir }}
        run: echo "deb [signed-by=/etc/apt/trusted.gpg.d/${{${{ env.list-name }}}}.gpg] https://${{ github.repository_owner }}.github.io/${{ env.base-dir }} ./" > "${{ env.list-name }}.list"

      - name: Commit and push
        shell: bash
        working-directory: ${{ env.base-dir }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "Nothing to commit"
          else
            git commit -m "Update PPA"
            git push
          fi

      - name: Summary
        run: |
          echo '# Add the PPA
          
          ```shell
          curl -s --compressed "https://${{ github.repository_owner }}.github.io/${{ env.base-dir }}/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/${{${{ env.list-name }}}}.gpg >/dev/null
          sudo curl -s --compressed -o /etc/apt/sources.list.d/${{ env.list-name }}.list "https://${{ github.repository_owner }}.github.io/${{ env.base-dir }}/${{ env.list-name }}.list"
          sudo apt update
          ```
          ' >> $GITHUB_STEP_SUMMARY
