name: Build PPA

on:
  workflow_dispatch:

jobs:
  package:
    name: Update PPA
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update PPA
        uses: csutorasa/ppa-pages@main
        with:
          base-dir: ppa
          list-name: csutorasa
          private-key: ${{ secrets.PRIVATE_KEY }}
