name: Build PPA

on:
  workflow_dispatch:

jobs:
  package:
    name: Update PPA
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update PPA
        uses: csutorasa/ppa-pages@main
        with:
          actor: ${{ github.actor }}
          actor-id: ${{ github.actor_id }}
          base-dir: ppa
          list-name: csutorasa
          private-key: ${{ secrets.PRIVATE_KEY }}
          repository-owner: ${{ github.repository_owner }}
